"""add document status

Revision ID: 9d0b176016c1
Revises: d0cda0f78ee3
Create Date: 2026-07-19 17:18:39.633627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d0b176016c1'
down_revision: Union[str, Sequence[str], None] = 'd0cda0f78ee3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'documents',
        sa.Column(
            'status',
            sa.String(length=20),
            nullable=True,
        )
    )

    op.execute(
        """
        UPDATE documents
        SET status = 'completed'
        WHERE status IS NULL
        """
    )

    op.alter_column(
        'documents',
        'status',
        nullable=False,
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'status')
    # ### end Alembic commands ###
